tasks:
- install:
- stone:
- rgw: [client.0]
- s3tests:
    client.0:
      force-branch: stone-pacific
      rgw_server: client.0
overrides:
  stone:
    conf:
      client:
        rgw lc debug interval: 10
