# Amazon::S3 is not available on el7
os_type: ubuntu
tasks:
- install:
- stone:
- rgw: [client.0]
- workunit:
    clients:
      client.0:
        - rgw/s3_multipart_upload.pl
overrides:
  stone:
    conf:
      client:
        rgw relaxed s3 bucket names: true
