overrides:
  stone:
    log-ignorelist:
      - missing required features
tasks:
- exec:
    mon.a:
      - stone fs dump --format=json-pretty
      - stone fs required_client_features stonefs add metric_collect
- sleep:
    duration: 5
- fs.clients_evicted:
