meta:
- desc: |
   install stone/octopus latest
tasks:
- install:
    branch: octopus
    exclude_packages:
      - librados3
      - stone-mgr-dashboard
      - stone-mgr-diskprediction-local
      - stone-mgr-rook
      - stone-mgr-stoneadm
      - stoneadm
    extra_packages: ['librados2']
- print: "**** done installing octopus"
- stone:
    log-ignorelist:
      - overall HEALTH_
      - \(FS_
      - \(MDS_
      - \(OSD_
      - \(MON_DOWN\)
      - \(CACHE_POOL_
      - \(POOL_
      - \(MGR_DOWN\)
      - \(PG_
      - \(SMALLER_PGP_NUM\)
      - Monitor daemon marked osd
      - Behind on trimming
      - Manager daemon
    conf:
      global:
        mon warn on pool no app: false
        ms bind msgr2: false
- exec:
    osd.0:
      - stone osd set-require-min-compat-client octopus
- print: "**** done stone"
