overrides:
  stone:
    log-ignorelist:
    - scrub mismatch
    - ScrubResult
    - wrongly marked
    - \(POOL_APP_NOT_ENABLED\)
    - \(SLOW_OPS\)
    - overall HEALTH_
    - \(MON_MSGR2_NOT_ENABLED\)
    - slow request
    conf:
      global:
        bluestore warn on legacy statfs: false
        bluestore warn on no per pool omap: false
      mon:
        mon warn on osd down out interval zero: false

tasks:
- print: "*** upgrading, no stonefs present"
- exec:
    mon.a:
    - stone fs dump
- install.upgrade:
    mon.a:
- print: "**** done install.upgrade"
- stone.restart:
    daemons: [mon.*, mgr.*]
    mon-health-to-clog: false
    wait-for-healthy: false
- stone.healthy:
- stone.restart:
    daemons: [osd.*]
    wait-for-healthy: false
    wait-for-osds-up: true
- exec:
    mon.a:
    - stone versions
    - stone osd dump -f json-pretty
    - stone fs dump
    - stone osd require-osd-release pacific
    - for f in `stone osd pool ls` ; do stone osd pool set $f pg_autoscale_mode off ; done
    #- stone osd set-require-min-compat-client octopus
- stone.healthy:
- print: "**** done stone.restart"
