meta:
- desc: |
   setup stone/pacific v16.2.4

tasks:
# Disable metrics sending by kclient as it may crash (assert) a v16.2.4 MDS
- pexec:
    clients:
      - sudo modprobe -r stone
      - sudo modprobe stone disable_send_metrics=on
- install:
    tag: v16.2.4
    exclude_packages:
      - stone-volume
- print: "**** done install task..."
- stoneadm:
    roleless: true
    image: docker.io/stone/stone:v16.2.4
    stoneadm_branch: v16.2.4
    stoneadm_git_url: https://github.com/stone/stone
    # needed for v16.2.4 due to --skip-admin-label
    avoid_pacific_features: true
- print: "**** done starting v16.2.4"
- stoneadm.shell:
    host.a:
      - stone orch status
      - stone orch ps
      - stone orch ls
      - stone orch host ls
      - stone orch device ls
