tasks:
- vip:

# make sure stoneadm notices the new IP
- stoneadm.shell:
    host.a:
      - stone orch device ls --refresh

# stop kernel nfs server, if running
- vip.exec:
    all-hosts:
      - systemctl stop nfs-server

- stoneadm.shell:
    host.a:
      - stone fs volume create foofs
      - stone nfs cluster create foo --ingress --virtual-ip {{VIP0}}/{{VIPPREFIXLEN}} --port 2999
      - stone nfs export create stonefs --fsname foofs --cluster-id foo --pseudo-path /fake

- stoneadm.wait_for_service:
    service: nfs.foo
- stoneadm.wait_for_service:
    service: ingress.nfs.foo

## export and mount

- vip.exec:
    host.a:
      - mkdir /mnt/foo
      - sleep 5
      - mount -t nfs {{VIP0}}:/fake /mnt/foo -o port=2999
      - echo test > /mnt/foo/testfile
      - sync

# take each gateway down in turn and ensure things still work
- stoneadm.shell:
    volumes:
      - /mnt/foo:/mnt/foo
    host.a:
      - |
        echo "Check with each haproxy down in turn..."
        for haproxy in `stone orch ps | grep ^haproxy.nfs.foo. | awk '{print $1}'`; do
          stone orch daemon stop $haproxy
          while ! stone orch ps | grep $haproxy | grep stopped; do sleep 1 ; done
          cat /mnt/foo/testfile
          echo $haproxy > /mnt/foo/testfile
          sync
          stone orch daemon start $haproxy
          while ! stone orch ps | grep $haproxy | grep running; do sleep 1 ; done
        done

# take each ganesha down in turn.
# simulate "failure" by deleting the container
- vip.exec:
    all-hosts:
      - |
        echo "Check with $(hostname) ganesha(s) down..."
        for c in `systemctl | grep stone- | grep @nfs | awk '{print $1}'`; do
            cid=`echo $c | sed 's/@/-/'`
            id=`echo $c | cut -d @ -f 2 | sed 's/.service$//'`
            fsid=`echo $c | cut -d @ -f 1 | cut -d - -f 2-`
            echo "Removing daemon $id fsid $fsid..."
            sudo $TESTDIR/stoneadm rm-daemon --fsid $fsid --name $id

            echo "Waking up stoneadm..."
            sudo $TESTDIR/stoneadm shell -- stone orch ps --refresh

            while ! timeout 1 cat /mnt/foo/testfile ; do true ; done
            echo "Mount is back!"
        done
