overrides:
  stone:
    conf:
      global:
        lockdep: true
    log-ignorelist:
      - missing required features
tasks:
  - stonefs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.stonefs.test_admin
