# The task interferes with the network, so we need
# to permit OSDs to complain about that.
overrides:
  stone:
    log-ignorelist:
      - evicting unresponsive client
      - but it is still running
      - slow request
      - MDS_CLIENT_LATE_RELEASE
      - t responding to mclientcaps
tasks:
  - stonefs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.stonefs.test_client_recovery
