overrides:
  stone:
    log-ignorelist:
      - bad backtrace
      - object missing on disk
      - error reading table object
      - error reading sessionmap
      - Error loading MDS rank
      - missing journal object
      - Error recovering journal
      - error decoding table object
      - failed to read JournalPointer
      - Corrupt directory entry
      - Corrupt fnode header
      - corrupt sessionmap header
      - Corrupt dentry
      - Scrub error on inode
      - Metadata damage detected
      - MDS_READ_ONLY
      - force file system read-only
tasks:
  - stonefs_test_runner:
      modules:
        - tasks.stonefs.test_damage

