overrides:
  stone:
    log-ignorelist:
      - bad backtrace
      - object missing on disk
      - error reading table object
      - error reading sessionmap
      - unmatched fragstat
      - unmatched rstat
      - was unreadable, recreating it now
      - Scrub error on inode
      - Metadata damage detected
      - inconsistent rstat on inode
      - Error recovering journal
tasks:
  - stonefs_test_runner:
      modules:
        - tasks.stonefs.test_data_scan
