overrides:
  stone:
    log-ignorelist:
      - inode wrongly marked free
      - bad backtrace on inode
      - inode table repaired for inode
      - Scrub error on inode
      - Metadata damage detected
tasks:
  - stonefs_test_runner:
      modules:
        - tasks.stonefs.test_forward_scrub
