overrides:
  stone:
    log-ignorelist:
      - client session with non-allowable root
tasks:
  - stonefs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.stonefs.test_sessionmap
