overrides:
  check-counter:
    dry_run: true
  stone:
    log-ignorelist:
      - evicting unresponsive client
      - RECENT_CRASH

tasks:
- exec:
    mon.a:
      - stone config set mgr mgr/crash/warn_recent_interval 0
- stonefs_test_runner:
    fail_on_skip: false
    modules:
      - tasks.stonefs.test_snapshots
