overrides:
  stone:
    conf:
      mgr:
        debug mgr: 20
        debug ms: 1
        debug finisher: 20
        debug client: 20
    log-whitelist:
      - OSD full dropping all updates
      - OSD near full
      - pausewr flag
      - failsafe engaged, dropping updates
      - failsafe disengaged, no longer dropping
      - is full \(reached quota
      - POOL_FULL
      - POOL_BACKFILLFULL

tasks:
  - stonefs_test_runner:
      modules:
        - tasks.stonefs.test_snap_schedules
