tasks:
- install.upgrade:
    client.0:
- print: "**** done install.upgrade on client.0"
- stone-fuse:
    client.0:
      mounted: false
    client.1:
      skip: true
- stone-fuse:
    client.0:
    client.1:
      skip: true
- print: "**** done remount client"
