
tasks:
  - install:
  - stone:
      # tests may leave mgrs broken, so don't try and call into them
      # to invoke e.g. pg dump during teardown.
      wait-for-scrub: false
      log-ignorelist:
        - overall HEALTH_
        - \(MGR_DOWN\)
        - \(MGR_INSIGHTS_WARNING\)
        - \(insights_health_check
        - \(PG_
        - \(RECENT_CRASH\)
        - replacing it with standby
        - No standby daemons available
  - stonefs_test_runner:
      modules:
        - tasks.mgr.test_insights
