#!/bin/sh

[ $# -lt 2 ] && echo "usage: $0 <name> <command> [params...]" && exit 1

root=`dirname $0`
run_name=$1
command=$2
STONE_BIN=$root
STONE_CONF_PATH=$root/run/$run_name

[ -z "$BUILD_DIR" ] && BUILD_DIR=build

if [ -e CMakeCache.txt ]; then
    STONE_BIN=$PWD/bin
    STONE_CONF_PATH=$PWD/run/$run_name
elif [ -e $root/../${BUILD_DIR}/CMakeCache.txt ]; then
    cd $root/../${BUILD_DIR}
    STONE_BIN=$PWD/bin
    STONE_CONF_PATH=$PWD/run/$run_name
fi

shift 2

if [ "$RGW_VALGRIND" == 'yes' ] && [ $command == 'radosgw' ]; then
    valgrind --trace-children=yes --tool=memcheck --max-threads=1024 $STONE_BIN/$command -c $STONE_CONF_PATH/stone.conf "$@"
    sleep 10
else
    $STONE_BIN/$command -c $STONE_CONF_PATH/stone.conf "$@"
fi

