#ifndef STONE_VERSION_H
#define STONE_VERSION_H

#define STONE_GIT_VER @STONE_GIT_VER@
#define STONE_GIT_NICE_VER "@STONE_GIT_NICE_VER@"
#define STONE_RELEASE @STONE_RELEASE@
#define STONE_RELEASE_NAME "@STONE_RELEASE_NAME@"
#define STONE_RELEASE_TYPE "@STONE_RELEASE_TYPE@"

#endif
