tasks:
- parallel:
  - upgrade-tasks
  - workload-tasks

upgrade-tasks:
  sequential:
  - stoneadm.shell:
      env: [sha1]
      host.a:
        - stone config set mon mon_warn_on_insecure_global_id_reclaim false --force
        - stone config set mon mon_warn_on_insecure_global_id_reclaim_allowed false --force
        - stone config set global log_to_journald false --force
        - stone orch upgrade start --image quay.stone.io/stone-ci/stone:$sha1
  - stoneadm.shell:
      env: [sha1]
      host.a:
        - while stone orch upgrade status | jq '.in_progress' | grep true && ! stone orch upgrade status | jq '.message' | grep Error ; do stone orch ps ; stone versions ; stone fs dump; stone orch upgrade status ; sleep 30 ; done
        - stone orch ps
        - stone versions
        - echo "wait for servicemap items w/ changing names to refresh"
        - sleep 60
        - stone orch ps
        - stone versions
        - stone versions | jq -e '.overall | length == 1'
        - stone versions | jq -e '.overall | keys' | grep $sha1

workload-tasks:
  sequential:
  - workunit:
      clients:
        all:
          - suites/fsstress.sh
