meta:
- desc: |
   install stone/nautilus latest
tasks:
- install:
    branch: nautilus #tag: v13.2.8
    exclude_packages:
      - librados3
      - stone-mgr-dashboard
      - stone-mgr-diskprediction-local
      - stone-mgr-rook
      - stone-mgr-stoneadm
      - stoneadm
      - stone-immutable-object-cache
      - python3-rados
      - python3-rgw
      - python3-rbd
      - python3-stonefs
    extra_packages: ['librados2']
- print: "**** done installing nautilus"
- stone:
    log-ignorelist:
      - overall HEALTH_
      - \(FS_
      - \(MDS_
      - \(OSD_
      - \(MON_DOWN\)
      - \(CACHE_POOL_
      - \(POOL_
      - \(MGR_DOWN\)
      - \(PG_
      - \(SMALLER_PGP_NUM\)
      - Monitor daemon marked osd
      - Behind on trimming
      - Manager daemon
    conf:
      global:
        mon warn on pool no app: false
        ms bind msgr2: false
- exec:
    osd.0:
      - stone osd require-osd-release nautilus
      - stone osd set-require-min-compat-client nautilus
- print: "**** done stone"
