overrides:
  stone:
    log-ignorelist:
      - missing required features
tasks:
- exec:
    mon.a:
      - stone fs dump --format=json-pretty
      - stone fs volume ls
      - stone fs subvolume ls stonefs
- workunit:
   clients:
     client.0:
     - fs/upgrade/volume_client
   env:
     ACTION: verify
   cleanup: false
- workunit:
   clients:
     client.1:
     - fs/upgrade/volume_client
   env:
     ACTION: verify
   cleanup: false
- print: "**** fs/volume_client verify"
