---
# Create a namespace to receive our test events
apiVersion: v1
kind: Namespace
metadata:
  name: stone
---
# Define the access rules to open the events API to k8sevents
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stone-mgr-events-rules
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
  - watch
  - patch
  - get
---
# Define a service account to associate with our event stream
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stone-mgr
  namespace: stone
---
# Allow the stone-mgr service account access to the events api
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stone-mgr
  namespace: stone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stone-mgr-events-rules
subjects:
- kind: ServiceAccount
  name: stone-mgr
  namespace: stone
